feat: updated RequestPostItem component to display status
reach4help/reach4help pull request #1059
Opened 2020-11-21 20:07 UTC by felix-chin

# Description

Updated RequestPostItem component to display the status of the requested item at the top right corner of the component. Added a useState hook to set the status, will need to be worked on further to handle the different status' to display based on user input in the app.

## Motivation

## Testing Guidelines

## Release Checklist

- [ ] This code has unit tests
- [ ] I have a plan to verify that these changes are working as expected after deploy
- [ ] I have a plan for how to revert, rollback, or disable these changes if things are not working as expected

## Security Checklist

This PR creates, modifies, or deletes:

- [ ] API routes: API routes, parameters, or user authorization
- [ ] Authentication: Authentication mechanism
- [ ] Credentials: Server side credentials, or secrets in configuration / source code
- [ ] Cryptography: Encryption, hashing, certificates, signatures, random numbers, etc.
- [ ] User data: personal information handling, logs, error messages, etc.

## Additional Notes

![Screenshot 2020-11-21 120250](https://user-images.githubusercontent.com/51896195/99886461-8c8b8a80-2bf1-11eb-9d6a-12318b68139b.png)

2020-11-25 14:05 UTC, ethanstrominger requested changes
See https://jira.reach4help.org/browse/REAC-133 for link to image of what it is supposed to look like.  The change should display status from Requests, no updates are required.

2020-12-01 19:10 UTC, felix-chin commented
@ethanstrominger I've made the changes we discussed the other day - the status should be coming from the request.status object now and the additional state I added has been removed.

2020-12-03 18:52 UTC, ethanstrominger approved these changes

2020-12-05 14:24 UTC, merged

2020-12-09 16:40 UTC, schowdhury8 commented
Thanks for the work, Felix! @all-contributors please add @felix-chin for code